version: "1"
services:
  frontend:
    image: frontend-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-app"
    volumes:
      - ./frontend/src:/app/src # para que el docker acceda a los ficheros del front
    ports:
      - "4200:4200"
  backend:
    image: backend-flask
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-app"
    volumes:
        - ./backend:/app #para que el docker acceda a los ficheros del back
    ports:
      - "8081:8081" # para el puerto de la api. Si lo cambiamos aquí debemos cambiarlo también en `frontend/proxy.conf.dev.json`
